version: '3.3'
services:
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
  application-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 3005:3005
volumes:
  cache:
    driver: local